### PR TITLE
added download icon and updated copy icon

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will add download option for conda lock and build log  and will use the icons from mdi
https://icon-sets.iconify.design/mdi/download/

### CODE REVIEW

**Comment by munishchouhan** [comment]
locally tested:

https://github.com/user-attachments/assets/16605358-6d59-436d-9e41-7de751f16fb0

**Comment by pditommaso** [comment]
Nice

**Comment by pditommaso** [comment]
let's add in this "base64 encode the PNG images and include inline too, rather than using external image files" as suggested in #650

**Comment by munishchouhan** [comment]
> let's add in this "base64 encode the PNG images and include inline too, rather than using external image files" as suggested in #650

ok sure

**Comment by munishchouhan** [comment]
tested again locally:

https://github.com/user-attachments/assets/e80d8b36-2dda-4186-a327-233aed512719

**Comment by munishchouhan** [comment]
@pditommaso I have made most of the changes asked in https://github.com/seqeralabs/wave/issues/650

**Comment by munishchouhan** [comment]
inspect view
Screenshot 2024-10-09 at 16 34 17

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Nice job 👍

**Pull request merged**
