### PR TITLE
Add scan failure duration setting

### PR DESCRIPTION
**Pull request by pditommaso**
This PR adds Scan failure duration setting

### CODE REVIEW

**Comment by pditommaso** [comment]
@munishchouhan quick double check on this ?

**Comment by munishchouhan** [comment]
> @munishchouhan quick double check on this ?

ok sure

**Comment by munishchouhan** [comment]
@pditommaso in case of build and mirror docker client retries, but how will this help in case of scan?
because there won't be a retry in this case.

**Comment by pditommaso** [comment]
Yeah, just realised the same.

**Comment by pditommaso** [comment]
Let me try one thing

**Comment by munishchouhan** [comment]
i tried like this
```
(base) munish.chouhan@Munishs-MacBook-Pro wavedevmemeoryissue % docker pull $(wave --conda-package bwa  --wave-endpoint http://localhost:9090 --platform linux/arm64 --scan-mode required --await)
Container provisioning did not complete successfully
- Reason: Container security scan did not complete successfully
- Find out more here: https://wave.eu.ngrok.io/view/scans/sc-4f9a5dbaddc1b1c4_1

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview 
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Download an image from a registry

```

**Comment by pditommaso** [comment]
Think it's needed to delete the `scanId` when there's a failure, otherwise it will continue to use the same. Please give a try the last push

**Comment by pditommaso** [comment]
It's not a retry, the scanId in the store should be deleted, so once there's a new request a new one is assigned e.g. xxx_1 -> xxx_2

**Comment by munishchouhan** [comment]
one thing i notice, even if i select --scan-mode required. log is printing:
`DEBUG i.s.w.controller.ContainerController - New container request fulfilled`

**Comment by pditommaso** [comment]
The problem was solved by this https://github.com/seqeralabs/wave/pull/705/commits/239fffd30710825cd01494598de7f0c5df46749b

**Pull request merged**
