### PR TITLE
Refactor build id & status endpoint

### PR DESCRIPTION
**Pull request by pditommaso**
This PR refactor the container build ID to ensure each request has a unique identifier and prevent conflicts for separate requests that may have failed due to a temporary failure. See for example https://github.com/seqeralabs/wave/issues/312.

### CODE REVIEW

**Comment by pditommaso** [comment]
The problem of this approach is that when a new request for the same container is submitted and the container is found in the repository, it returns an id that's not matching the build, and therefore, following requests will fail (e.g for logs, status, etc)

**Comment by pditommaso** [comment]
@munishchouhan can you please make some build tests with this branch? in principle should also solve #312

**Comment by munishchouhan** [comment]
> @munishchouhan can you please make some build tests with this branch? in principle, should also solve #312

Yes, I am currently working on it., Sorry, I should have mentioned my progress here 
1. success build
Screenshot 2024-03-21 at 12 25 10

2. failed build

Screenshot 2024-03-21 at 12 26 29
3. pending build
Screenshot 2024-03-21 at 12 29 49

will comment here with more cases

**Comment by munishchouhan** [comment]
4. pending build failed
Screenshot 2024-03-21 at 12 34 44

5. second pending build
Screenshot 2024-03-21 at 12 43 06

6. second build succeeded 
Screenshot 2024-03-21 at 12 46 13

**Comment by munishchouhan** [comment]
@pditommaso I am not sure if its a valid user case, but when I delete image from the repository and the entry is still present in cache, a new buildid get generated but it does not return anything

Log:
`== Hit build cache for request: BuildRequest[containerId=469775171e19891b; targetImage=hrma017/dev:my_env--469775171e19891b; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null); dockerFile=FROM mambaorg/micromamba:1.5.5 (more omitted); condaFile=name: my_env (more omitted); spackFile=null; buildId=469775171e19891b_2]`

API call:
Screenshot 2024-03-21 at 12 59 10

I think in this case new build process doesn't start only build is gets generated

**Comment by pditommaso** [comment]
> I am not sure if its a valid user case, but when I delete image from the repository and the entry is still present in cache, a new buildid get generated but it does not return anything

This is already happening. Let's ignore it for now. 

Apart this, I'm understanding everything else is working properly. Is that correct?

**Comment by munishchouhan** [comment]
> > I am not sure if its a valid user case, but when I delete image from the repository and the entry is still present in cache, a new buildid get generated but it does not return anything
> 
> This is already happening. Let's ignore it for now.
> 
> Apart this, I'm understanding everything else is working properly. Is that correct?

Yes

**Review by munishchouhan — APPROVED** [review]

**Comment by munishchouhan** [comment]
@pditommaso It does not restart the last failed build 

```
14:20:23.532 [io-executor-thread-2] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Submit build request: BuildRequest[containerId=469775171e19891b; targetImage=hrma017/dev:my_env--469775171e19891b; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null); dockerFile=FROM mambaorg/micromamba:1.5.5 (more omitted); condaFile=name: my_env (more omitted); spackFile=null; buildId=469775171e19891b_1]
14:20:23.570 [io-executor-thread-1] DEBUG i.s.w.s.builder.DockerBuildStrategy - Build run command: docker run --rm -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/469775171e19891b_1:/Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/469775171e19891b_1 -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/469775171e19891b_1/config.json:/kaniko/.docker/config.json:ro --platform linux/amd64 gcr.io/kaniko-project/executor:v1.19.2 --dockerfile /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/469775171e19891b_1/Containerfile --context /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/469775171e19891b_1/context --destination hrma017/dev:my_env--469775171e19891b --cache=true --custom-platform linux/amd64 --cache-repo hrma017/cache
14:20:23.573 [io-executor-thread-2] DEBUG i.s.w.c.ContainerTokenController - New container request fulfilled - token=f9f7290e66d4; expiration=2024-03-21T14:20:23.565791Z; container=hrma017/dev:my_env--469775171e19891b; build=469775171e19891b_1; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null)
14:20:27.250 [io-executor-thread-1] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Build request 469775171e19891b_1 completed with status=143
14:21:12.121 [io-executor-thread-3] DEBUG i.s.w.s.i.ContainerInspectServiceImpl - Build credentials for repository: hrma017/dev => RegistryCredentials[username=hrma017; password=dck****]
14:21:12.124 [io-executor-thread-3] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=docker.io/hrma017/dev:my_env--469775171e19891b; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null) => RegistryCredentials[username=hrma017; password=dck****]
14:21:12.562 [io-executor-thread-3] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Hit build cache for request: BuildRequest[containerId=469775171e19891b; targetImage=hrma017/dev:my_env--469775171e19891b; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null); dockerFile=FROM mambaorg/micromamba:1.5.5 (more omitted); condaFile=name: my_env (more omitted); spackFile=null; buildId=469775171e19891b_2]
14:21:12.565 [io-executor-thread-3] DEBUG i.s.w.c.ContainerTokenController - New container request fulfilled - token=90337dde10d3; expiration=2024-03-21T14:21:12.563145Z; container=hrma017/dev:my_env--469775171e19891b; build=null; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null)
```

**Comment by pditommaso** [comment]
>  It does not restart the last failed build

Not understanding

**Comment by munishchouhan** [comment]
as per [312](https://github.com/seqeralabs/wave/issues/312)
reattempt to build the same image, which failed last time, should be completed next time.
But that is not happening.

I started the build and stopped the docker in between to make it fail and then sent the same request again, but only a new build id gets generated but no image build.

**Comment by pditommaso** [comment]
I see, worth debugging it

**Comment by munishchouhan** [comment]
> I see, worth debugging it

sure, I will do that

**Comment by munishchouhan** [comment]
I did create a PR sometime back to fix this issue, I will reapply and check if it still works
https://github.com/seqeralabs/wave/pull/362

**Comment by munishchouhan** [comment]
@pditommaso I have created a PR to fix the restart build, please check
https://github.com/seqeralabs/wave/pull/428

**Pull request merged**
