### PR TITLE
Remove ip address

### PR DESCRIPTION
**Pull request by pditommaso**
This PR removes the ip address from container page

### CODE REVIEW

**Review by ewels — APPROVED** [review]

**Comment by pditommaso** [comment]
tagging @munishchouhan for help

**Comment by munishchouhan** [comment]
> tagging @munishchouhan for help

ok sure, i will fix the tests

**Comment by munishchouhan** [comment]
tested
Screenshot 2024-10-09 at 18 10 24

**Comment by munishchouhan** [comment]
@pditommaso  i cannot merge because all commits are not signed

**Pull request merged**
