### PR TITLE
Add v1alpha2 request endpoint

### PR DESCRIPTION
**Pull request by pditommaso**
This PR add a draft implementation for v1alpha2 version of container request endpoint. 

The main differences are: 
1. Conda and packages/file are expected to be provided via the [packages](https://github.com/seqeralabs/libseqera/blob/505a3642395c05fe048b7cf49dc015ac7a4d9772/wave-api/src/main/java/io/seqera/wave/api/SubmitContainerTokenRequest.java#L140-L140) attribute instead of `condaFile` and `spackFile` 
2. When `packages` is specified, [containerFile](https://github.com/seqeralabs/libseqera/blob/505a3642395c05fe048b7cf49dc015ac7a4d9772/wave-api/src/main/java/io/seqera/wave/api/SubmitContainerTokenRequest.java#L61-L61) should not be provided 
3. Wave will need to create the required `containerFile` instead for the given packages, in a similar manner as it's done now [here](https://github.com/seqeralabs/wavelit/blob/f5d6d9a5902cd5ca06392bdf8364b07d4f08c0be/app/src/main/java/io/seqera/wave/cli/App.java#L587-L608)

### CODE REVIEW

**Comment by pditommaso** [comment]
@munishchouhan Have a look at this at your convenience. Let me know if something is not clear

**Comment by munishchouhan** [comment]
connected PR

**Comment by munishchouhan** [comment]
@pditommaso in cli conda channels and provided through options
https://github.com/seqeralabs/wave-cli/blob/f5d6d9a5902cd5ca06392bdf8364b07d4f08c0be/app/src/main/java/io/seqera/wave/cli/App.java#L592

How are we getting them in Wave?

**Comment by pditommaso** [comment]
Likely will need to add `List<String> channels` to `PackagesSpec`

**Comment by munishchouhan** [comment]
Testing the changes in my local machine

**Comment by munishchouhan** [comment]
1. Tested for conda packages without a remote conda lock file and image created and uploaded successfully

Screenshot 2024-03-18 at 14 37 12
Screenshot 2024-03-18 at 14 38 12

**container file:**

Screenshot 2024-03-18 at 14 40 53


**conda.yml file**

Screenshot 2024-03-18 at 14 40 47

**Comment by munishchouhan** [comment]
2. Test singularity build with conda packages
Screenshot 2024-03-18 at 15 17 45
Screenshot 2024-03-18 at 15 17 54

containerfile:
Screenshot 2024-03-18 at 15 18 35

**Comment by munishchouhan** [comment]
3. Test singularity and freeze with spack
Screenshot 2024-03-18 at 17 03 53

spack file:
Screenshot 2024-03-18 at 17 05 03

containerfile:
Screenshot 2024-03-18 at 17 06 05

**Comment by munishchouhan** [comment]
4. Test using docker and spack packages:
Screenshot 2024-03-18 at 17 07 19

spack file:
Screenshot 2024-03-18 at 17 08 18

container file:
Screenshot 2024-03-18 at 17 09 26

**Comment by munishchouhan** [comment]
Tested using envFile:
Screenshot 2024-03-19 at 15 43 59
Screenshot 2024-03-19 at 15 44 33
condafile:
Screenshot 2024-03-19 at 15 45 09
containerfile:
Screenshot 2024-03-19 at 15 46 15

**Comment by pditommaso** [comment]
I've made a refactor to minimise the changes in the logic of the endpoint v1 vs v2. 

The main difference consists resolving the `containerFile` from the `packages` attribute and and retrofitting in the request [here](https://github.com/seqeralabs/wave/blob/2054d896c4500c79f7e4c8426bec80ecc2330488/src/main/groovy/io/seqera/wave/controller/ContainerTokenController.groovy#L195-L199), so that it should be possible to apply almost the same logic. 

I've also update the client in this [PR](https://github.com/seqeralabs/wave-cli/pull/62). @munishchouhan please give it a try, there should be some tests to be fixed

**Comment by munishchouhan** [comment]
testing is getting done in https://github.com/seqeralabs/wave-cli/pull/62

**Comment by munishchouhan** [comment]
Testing completed, everything is working fine

**Comment by ewels** [comment]
Where are the default channels listed?

Reminder that Bioconda [recommends](https://bioconda.github.io/#usage) having 3:

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

Eqivalent to `['conda-forge', 'bioconda', 'defaults']` I think.

**Comment by munishchouhan** [comment]
> Where are the default channels listed?
> 
> Reminder that Bioconda [recommends](https://bioconda.github.io/#usage) having 3:
> 
> ```shell
> conda config --add channels defaults
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda config --set channel_priority strict
> ```
> 
> Eqivalent to `['conda-forge', 'bioconda', 'defaults']` I think.

@ewels  default channels: "seqera,conda-forge,bioconda,defaults"

**Comment by munishchouhan** [comment]
> @ewels default channels: "seqera,conda-forge,bioconda,defaults"

@ewels sorry, there is a correction, these channels are defined in wave-cli, we do not have any default conda channel in wave

**Comment by pditommaso** [comment]
I think it's client responsability to specify the channels

**Comment by pditommaso** [comment]
Think we are almost there with this. @munishchouhan can you please make a bit more tests using both the old and new version of the client? 

It would also be nice to add some tests for [this method](https://github.com/seqeralabs/wave/blob/1af9953b764408378c530378661a7e22baa8f2ad/src/main/groovy/io/seqera/wave/controller/ContainerHelper.groovy#L159-L166) along the same manner as it has been done [here](https://github.com/seqeralabs/wave/blob/1af9953b764408378c530378661a7e22baa8f2ad/src/test/groovy/io/seqera/wave/controller/ContainerHelperTest.groovy#L314-L342)

**Comment by munishchouhan** [comment]
> Think we are almost there with this. @munishchouhan can you please make a bit more tests using both the old and new version of the client?
> 
> It would also be nice to add some tests for [this method](https://github.com/seqeralabs/wave/blob/1af9953b764408378c530378661a7e22baa8f2ad/src/main/groovy/io/seqera/wave/controller/ContainerHelper.groovy#L159-L166) along the same manner as it has been done [here](https://github.com/seqeralabs/wave/blob/1af9953b764408378c530378661a7e22baa8f2ad/src/test/groovy/io/seqera/wave/controller/ContainerHelperTest.groovy#L314-L342)

ok sure

**Comment by munishchouhan** [comment]
@pditommaso I did testing with await and all were successful posted the results here
https://github.com/seqeralabs/wave-cli/pull/62#issuecomment-2037204796

**Comment by munishchouhan** [comment]
@pditommaso one problem is found when the image is no longer in the repo, and the cache is invalidated. even though wave does starts the rebuild but await doesn't work with the new endpoint. Because now in status endpoint we check the status from database, which persists the entry for that container

**Comment by ewels** [comment]
> I think it's client responsability to specify the channels

If we're only providing package names here (not conda env files) then many installs simply won't work without the proper channel configuration.

**Comment by pditommaso** [comment]
What's preventing the client to provide the default channels?

**Comment by marcodelapierre** [comment]
Both the Nextflow Wave Client and Wave CLI allow specifying conda channels, though in slightly different ways.    

Wave CLI also has the usual default set `seqera,conda-forge,bioconda,defaults`, whereas with Nextflow there is no default. We could add the same default, as well as an option `wave.build.conda.channels` to change it.  Should be Wave specific, because with Nextflow there is also the use case of host conda builds, where channel configurations could come from different places.

@ewels @pditommaso ?

**Comment by marcodelapierre** [comment]
> @pditommaso one problem is found when the image is no longer in the repo, and the cache is invalidated. even though wave does starts the rebuild but await doesn't work with the new endpoint. Because now in status endpoint we check the status from database, which persists the entry for that container

@munishchouhan  When the image is gone and a new build is required, will this new rebuild have a new ID?  If so, then Wave CLI --await should ping for the new build ID, right?

**Comment by ewels** [comment]
Ok as long as we're able to set a default somewhere I guess it doesn't matter too much whether that's client or endpoint 👍🏻

**Comment by munishchouhan** [comment]
> @munishchouhan When the image is gone and a new build is required, will this new rebuild have a new ID? If so, then Wave CLI --await should ping for the new build ID, right?

@marcodelapierre  buildId remains same and I checked in the DB and there are multiple records for same buildID 
```
seqera/wave> select buildId, count() from wave_build group by buildId ;
[[{ buildId: 'bc09f242935a6cd3_1', count: 3 }, { buildId: 'ffb67fece4121774_1', count: 5 }]]
```

**Comment by munishchouhan** [comment]
The entries in the database are correct because wave creates new buildId by checking the cache and not the DB, so if there is no image in the repository and the cache entry has been invalidated.

**Comment by pditommaso** [comment]
Ready

**Pull request merged**
