### PR TITLE
Add code coverage report to build

### PR DESCRIPTION
**Pull request by pditommaso**
This PR adds the jacoco plugin to create code coverage reports

### CODE REVIEW

**Comment by pditommaso** [comment]
@munishchouhan can you have a look how to grab the code cov report file and include in the CI build download page?

**Comment by pditommaso** [comment]
[This](https://github.com/marketplace/actions/jacoco-report) may be useful. Credits @swampie

**Comment by munishchouhan** [comment]
> @munishchouhan can you have a look how to grab the code cov report file and include in the CI build download page?

ok sure

**Comment by munishchouhan** [comment]
code coverage is getting printed in the action console, but not getting commented in PR
I am trying different GH token to see if it is permission issue
Screenshot 2024-10-02 at 14 51 20

**Comment by munishchouhan** [comment]
code coverage report is successfully published
Screenshot 2024-10-02 at 15 40 18

Screenshot 2024-10-02 at 15 40 05

**Comment by pditommaso** [comment]
Awesome

**Pull request merged**
