### PR TITLE
Check block existence with object operation

### PR DESCRIPTION
**Pull request by pditommaso**
This PR change the logic for checking the existence of blob cache by using S3 operation instead of HTTP head method. 

This is needed to prevent that the result of the HTTP HEAD check for a non-existing object retuning 404 (not found) is cached by the underlying caching rule as documented [here](https://developers.cloudflare.com/r2/reference/consistency/#caching). 

The of S3 API should bypass the caching layer and therefore preventing this issue.

### CODE REVIEW

**Comment by pditommaso** [comment]
@munishchouhan can you give it a try at your convenience. Tagging @gavinelder for visibility.

**Comment by munishchouhan** [comment]
There is a problem with my colima setup using other option to test it

**Comment by munishchouhan** [comment]
Tested locally 
successfully with 10 parallel transfers:
Screenshot 2024-11-20 at 12 36 00

**Comment by munishchouhan** [comment]
cache:
Screenshot 2024-11-20 at 12 37 26

**Comment by munishchouhan** [comment]
tested blob exists:
Screenshot 2024-11-20 at 13 43 56

**Review by munishchouhan — APPROVED** [review]

**Pull request merged**
