### PR TITLE
Container blob cache

### PR DESCRIPTION
**Pull request by pditommaso**
This PR implements a caching mechanism for layer blobs to achieve to main goals: 
- deduplicate the downloads of the same binary layers 
- offload the download of blob binaries to the S3 bucket. 

The overall logic is very similar to the one implemented by [ContainerBuildServiceImpl](https://github.com/seqeralabs/wave/blob/049a20763b875a6bd6b99bf456a3037a5b329c26/src/main/groovy/io/seqera/wave/service/builder/ContainerBuildServiceImpl.groovy#L67-L67), implementing the download and storing to S3 instead of building the image 

Solves https://github.com/seqeralabs/wave/issues/338

### CODE REVIEW

**Comment by pditommaso** [comment]
Ready for testing. The blob caching is enabled by settings in the application config 

```
wave:
  blobCache:
    enabled: true
    baseUrl: "https://cache-bucket-name-hostname"
    storage:
      bucket: "s3://<cache-bucket-name>"
```

When this feature is enabled, Wave caches the container blob binaries in the `cache-bucket-name` bucket specified in the above setting and returns an HTTP 307 redirect response with the URL of the cache blob content. 

The upload to the object storage is made via [s5cmd](https://github.com/seqeralabs/wave/blob/4933e158d3df72f83f5d0f386b36674593c712c5/src/main/resources/application.yml#L74-L74) run in a (pod) container. This avoid overloading the Wave backend with memory-intensive binary transfer operations. 

The use of a CDN network such as CloudFront or Cloudflare can be used to further optimise the caching and download of the container binaries

**Comment by pditommaso** [comment]
To complete this feature, we may need to generate [signed URL](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3-presign.html) for the objects stored in the S3 bucket so that they will be accessible only for a specified period of time. 

Likely the logic should be implemented [here](https://github.com/seqeralabs/wave/blob/2e3e847b9750ce7563190a09183d183387065096/src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy#L211-L213). 

@munishchouhan want to give a try to this?

**Comment by munishchouhan** [comment]
> To complete this feature, we may need to generate [signed URL](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3-presign.html) for the objects stored in the S3 bucket so that they will be accessible only for a specified period of time.
> 
> Likely the logic should be implemented [here](https://github.com/seqeralabs/wave/blob/2e3e847b9750ce7563190a09183d183387065096/src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy#L211-L213).
> 
> @munishchouhan want to give a try to this? (please use a separate PR)

sure

**Comment by marcodelapierre** [comment]
Wooo it's merged, well done folks!! 🚀

**Pull request merged**
