### PR TITLE
enabled reuse in spack

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will enable spack to reuse already build packages

### CODE REVIEW

**Comment by bebosudo** [comment]
I converted it to draft while we wait for Marco to comment, just to make sure we're all on the same page.

**Comment by marcodelapierre** [comment]
@munishchouhan apol for the wait, I will be on this on Monday, this week has been onboarding, setup, sort out the context.. will hear from me 🙂

**Comment by pditommaso** [comment]
@marcodelapierre please have a look at this

**Review by marcodelapierre — APPROVED** [review]
all good.

I have committed a small change, turning `reuse:true` in two instances of unit tests, for consistency.

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
