### PR TITLE
Update metric service to get aggregated metrics 

### PR DESCRIPTION
**Pull request by munishchouhan**
closes https://github.com/seqeralabs/wave/issues/469
This PR will add the following
1. This PR will add a function in counterProvider to get all matching data data using hscan
2. This will add a method in metric service to get the count per org and total count
3. Add new model for the response

When no date or ord is provided then metrics endpoint will return the above

### CODE REVIEW

**Comment by munishchouhan** [comment]
Tested successfully in local
Screenshot 2024-04-24 at 16 34 38
Screenshot 2024-04-24 at 16 44 27

Screenshot 2024-04-24 at 16 42 28

**Comment by munishchouhan** [comment]
Working on only getting the /metrics/o records from redis

**Comment by munishchouhan** [comment]
> Working on only getting the /metrics/o records from redis

Hscan uses glob pattern, so we need to get all the records in metrics/o/ and then filter out the relevant ones

**Comment by munishchouhan** [comment]
@pditommaso its ready for review

**Comment by pditommaso** [comment]
Got an error trying this 

```
» curl -u foo:bar http://localhost:9090/v1alpha2/metrics/fusion/pulls
{"message":"Cannot invoke \"java.util.Map.entrySet()\" because \"self\" is null - Error ID: 375c044c6d5f"}
```

**Comment by munishchouhan** [comment]
> Got an error trying this
> 
> ```
> » curl -u foo:bar http://localhost:9090/v1alpha2/metrics/fusion/pulls
> {"message":"Cannot invoke \"java.util.Map.entrySet()\" because \"self\" is null - Error ID: 375c044c6d5f"}
> ```

fixed

**Comment by pditommaso** [comment]
Ok, nice

**Pull request merged**
