### PR TITLE
Bump version 1.2.0-SPACK-M2

### PR DESCRIPTION
**Pull request by pditommaso**
This is baseline PR to collect all changes related to Spack support milestone 2.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
@bebosudo 

this is the new have-it-all Spack PR for Wave .  

So, this is the one that
- updates Spack version to `develop` for base image and binary cache
- contain the changes that will reflect also on your binary cache population runs.


For consistency, I suggest to bump update the container images above to 
```
cr.seqera.io /public/spack/spack/ubuntu-jammy:devlop
```


- https://github.com/seqeralabs/infrastructure/blob/4232145b82c9f3e888eeb34cdfd5cfa6e8d12645/.github/workflows/spack-mirror.yaml#L12
- https://github.com/seqeralabs/test-nf-tower-cloud-gha-dev-branch-pr/blob/55b26328a50e8c91c241e0b404dc484d99e4f731/.github/workflows/spack-mirror.yaml#L12

and finally, make sure that image is available in our registry (not the case right now).   Thank you

**Comment by marcodelapierre** [comment]
@bebosudo continuing the conversation here from #385, as this is the PR still in progress (other got merged here).


Oops my previous message lacked some info. I was just suggesting to make sure that these other two locations across the codebases also point to the `cr.seqera.io /public/spack/spack/ubuntu-jammy:devlop` image:

- https://github.com/seqeralabs/infrastructure/blob/4232145b82c9f3e888eeb34cdfd5cfa6e8d12645/.github/workflows/spack-mirror.yaml#L12
- https://github.com/seqeralabs/test-nf-tower-cloud-gha-dev-branch-pr/blob/55b26328a50e8c91c241e0b404dc484d99e4f731/.github/workflows/spack-mirror.yaml#L12


On the public availability of the images. 

This works for me:
```
$ docker pull cr.seqera.io/public/spack/spack/ubuntu-jammy:v0.20.0
v0.20.0: Pulling from public/spack/spack/ubuntu-jammy
...
```

but other tags do not work:
```
$ docker pull cr.seqera.io/public/spack/spack/ubuntu-jammy:develop
Error response from daemon: unknown: artifact public/spack/spack/ubuntu-jammy:develop not found
```


Does it make more sense now?

**Comment by bebosudo** [comment]
> but other tags do not work:
> 
> ```
> $ docker pull cr.seqera.io/public/spack/spack/ubuntu-jammy:develop
> Error response from daemon: unknown: artifact public/spack/spack/ubuntu-jammy:develop not found
> ```

The correct location is `cr.seqera.io/spack/spack/ubuntu-jammy:develop` without the extra `/public` prefix, the explanation is in [this comment](https://github.com/seqeralabs/wave/pull/385#issuecomment-1909790682).
I removed the test repo and image at `cr.seqera.io/public/spack/spack/ubuntu-jammy` to avoid further confusion, since the correct location is the one above. Feel free to replace it wherever a wrong location is used. The location above allows us to update the image on aws without the need to use harbor credentials. PR #385 is already using the correct location.

**Comment by marcodelapierre** [comment]
Thanks for re-explaining @bebosudo , I hadn't noticed the difference in repository naming, all clear!

**Comment by marcodelapierre** [comment]
This one needs updating then: https://github.com/seqeralabs/test-nf-tower-cloud-gha-dev-branch-pr/blob/master/.github/workflows/spack-mirror.yaml#L12

The PR in Wave is setting the version to be used to `develop`; when it gets merged by Paolo, with the change above we will be able to perform all tests by consistenly using the `develop` tag.

**Comment by pditommaso** [comment]
Closing as Spack support will not be maintained anymore

**Pull request closed without merging**
