### PR TITLE
Deprecate the support for Spack and remove the support for it in the codebase

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will deprecate the support for Spack and remove the support for it in the codebase

### CODE REVIEW

**Comment by gwright99** [comment]
Out of curiosity, why the deprecation? IIRC the development team put quite a bit of work into this only just a few months ago.

**Comment by munishchouhan** [comment]
> Out of curiosity, why the deprecation? IIRC the development team put quite a bit of work into this only just a few months ago.

here is the justification
https://github.com/seqeralabs/wave/issues/531#issue-2351287592

**Comment by munishchouhan** [comment]
@pditommaso should i remove the code specific to spack or just change documentation and deprecate methods and classes?

**Comment by pditommaso** [comment]
Let's starting updating the docs and marking the classes as deprecated

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
