### PR TITLE
Fix/wavespack quiet filestrip

### PR DESCRIPTION
**Pull request by marcodelapierre**
This PR will fix the error thrown by strip command in wave spack template

### CODE REVIEW

**Comment by marcodelapierre** [comment]
This PR will fix the error thrown by strip command in wave spack template

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
and the build failed!

**Comment by pditommaso** [comment]
```
Condition not satisfied:

build.id == '305f7f871d02e3d1'
|     |  |
|     |  false
|     |  14 differences (12% similarity)
|     |  (b7d-)7(30d2)7(4)d(1-)e(057)
|     |  (305f)7(f8--)7(1)d(02)e(3d1)
|     b7d730d274d1e057
BuildRequest[id=b7d730d274d1e057; targetImage=wave/build:b7d730d274d1e057; user=null; dockerFile=# Builder image (more omitted); condaFile=null; spackFile=some::spack-recipe]

	at io.seqera.wave.controller.ContainerTokenControllerTest.should create build request(ContainerTokenControllerTest.groovy:259)
```

**Comment by munishchouhan** [comment]
Pr to fix this
https://github.com/seqeralabs/wave/pull/322

**Comment by marcodelapierre** [comment]
apol for the hiccup Paolo 

why didn't the CI tests run for this PR? 
(I skipped running the unit tests locally, assuming they would have run)

**Comment by pditommaso** [comment]
I wanted to ask you 😆

**Comment by marcodelapierre** [comment]
ahah lol - I made no tricks I swear!! 😂

**Comment by munishchouhan** [comment]
CI were skipped in the second commit

**Comment by munishchouhan** [comment]
> CI was skipped in the second commit

Maybe because the changes are only whitespaces in that commit

**Comment by marcodelapierre** [comment]
Ha! I hacked the system 😂 

Thanks Munish, I will run the tests locally next time, if the Github ones are skipped

**Pull request merged**
