### PR TITLE
Add visibility into API rate limits

### PR DESCRIPTION
**Pull request by jason-seqera**
This content is also included already for the CLI.

- https://github.com/seqeralabs/nf-tower-docs/issues/477

### CODE REVIEW

**Comment by gwright99** [comment]
@jason-seqera - it's been two months since the source ticket was opened. Kindly:

1. Advise if Engineering/Product have provided confirmation that these values have not changed.
2. If knock-on documentation work needs to occur as a result of recent (Dec 4th) communications between @Shahbaz-mahmood123 and @marcodelapierre on the source ticket.

Thanks

**Comment by jason-seqera** [comment]
These might live here: `src/main/resources/application-rate-limit.yml`.

@munishchouhan, can these be overwritten when the service is deployed? Or is this file authoritative for what limits are in place?

Thanks!

**Comment by msnyder0693** [comment]
@gwright99 confirmed today- any change to values will be encompassed in the technical review stage which will be done by an engineer for this issue.

**Comment by munishchouhan** [comment]
> These might live here: `src/main/resources/application-rate-limit.yml`.
> 
> @munishchouhan, can these be overwritten when the service is deployed? Or is this file authoritative for what limits are in place?

its a configuration for rate limits and can be changed while deploying wave

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
