### PR TITLE
Log collapse

### PR DESCRIPTION
**Pull request by pditommaso**
This PR enables to collapse of multi-lines log entries e.g. exception stack traces in a sole entry when reported by Grafana. 

See also [here](https://grafana.com/docs/loki/latest/send-data/promtail/stages/multiline/#custom-log-format) and related [backlog ticket](https://github.com/seqeralabs/devops-backlog/issues/408)

### CODE REVIEW

**Comment by pditommaso** [comment]
@munishchouhan it would be nice if you could have a look at this

**Comment by munishchouhan** [comment]
@pditommaso as I understand promptail is expecting a `[` at the start of every first line.
Did we already test it after adding a square bracket for the timestamp?

**Comment by pditommaso** [comment]
I think this branch manages it correctly on Wave side. Not sure promtail is configured correctly instead. See my [comment here](https://github.com/seqeralabs/devops-backlog/issues/408#issuecomment-2047927990). I'd suggest to interact with @ashseqera and test in the dev cluster

**Comment by munishchouhan** [comment]
I tried with the changes in dev, but still the same result, I checked with @bebosudo but no luck. @ashseqera is on leave today So, for now I will try to setup something in local to test 
Screenshot 2024-04-12 at 15 21 27

**Comment by munishchouhan** [comment]
this is more clear
Screenshot 2024-04-12 at 15 38 06

**Comment by munishchouhan** [comment]
@pditommaso its working in my local with current these changes
Screenshot 2024-04-12 at 18 14 21

**Comment by munishchouhan** [comment]
@ashseqera This is my promtail config
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - multiline:
          firstline: '^\x{200B}\['
          max_wait_time: 3s
    static_configs:
      - targets:
          - localhost
        labels:
          job: wavelogs
          host: wave
          __path__: /Users/munish.chouhan/main_ground/wave/424/wave/*.log

```

**Comment by munishchouhan** [comment]
Note: in my local i am reading from log file, so I have made changes in file appended
```
    <appender name="ROLLING_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${WAVE_LOG_ROOT}/${WAVE_LOG_NAME}.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${WAVE_LOG_NAME}.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 10 days' worth of history capped at 100MB total size -->
            <maxHistory>10</maxHistory>
            <totalSizeCap>200MB</totalSizeCap>
        </rollingPolicy>
        <encoder>
            <pattern>&ZeroWidthSpace;[%d{HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="ROLLING_FILE" />
    </root>
</configuration>
```

**Comment by pditommaso** [comment]
Excellent! it would be nice to get rid of the need of zero blank space and the square brackets, see [here](https://github.com/seqeralabs/wave/pull/449/files#diff-33255c198beb505875429994308ac79fd2a34e56bf81f6a7794dec3687790441R33), and instead use a regex to match the timestamp as the do there [here](https://grafana.com/docs/loki/latest/send-data/promtail/stages/multiline/#predefined-log-format) 

```
- multiline:
    # Identify timestamps as first line of a multiline block. Enclose the string in single quotes.
    firstline: '^\[\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\]'
    max_wait_time: 3s
```

**Comment by munishchouhan** [comment]
it works with this config
```
    pipeline_stages:
      - multiline:
          firstline: '^\[\d{2}:\d{2}:\d{2}.\d{3}\]'
          max_wait_time: 3s
```
Screenshot 2024-04-12 at 18 43 38

**Comment by munishchouhan** [comment]
Does not worked in dev
Screenshot 2024-04-15 at 10 56 56

**Comment by pditommaso** [comment]
Ouch, different Loki version or config?

**Comment by munishchouhan** [comment]
> Ouch, different Loki version or config?

I will collaborate with @ashseqera to find out more

**Comment by munishchouhan** [comment]
promtail version is 2.8.3 in dev, so that's not an issue because it supports multiline
https://artifacthub.io/packages/helm/grafana/promtail/6.11.9
https://grafana.com/docs/loki/v2.8.x/clients/promtail/stages/multiline/

made changes to config format I here, but still no luck
https://github.com/seqeralabs/platform-deployment/pull/332

**Comment by munishchouhan** [comment]
After some digging, we found that the new config is not being reflected in the dev monitoring after deployment, so that might the underlying issue

**Comment by munishchouhan** [comment]
@pditommaso wokring in dev now
Screenshot 2024-04-16 at 17 19 34

**Comment by pditommaso** [comment]
Excellent! let's move forward to stage

**Comment by munishchouhan** [comment]
It's a global config, so checking for tower-dev too.
https://github.com/seqeralabs/platform-deployment/pull/332

**Comment by pditommaso** [comment]
what's the status of this? about all I think this is not needed anymore because the change is purely on promptail config, right?

**Comment by munishchouhan** [comment]
> what's the status of this? about all I think this is not needed anymore because the change is purely on promptail config, right?

yes, no change needed in wave. closing it

**Pull request closed without merging**
