### PR TITLE
add API and UI to evict a wave request from token cache  

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will add functionality in wave to and entry in cache against a token.
1. Expose authenticated delete API to evict the entry 
2. UI to do the same

### CODE REVIEW

**Comment by pditommaso** [comment]
Can the button look like the one in [this comment](https://github.com/seqeralabs/wave/issues/409#issuecomment-1966591630) 

Screenshot 2024-03-11 at 18 37 03

**Comment by munishchouhan** [comment]
@pditommaso is this ok?
Screenshot 2024-03-11 at 19 46 28

**Comment by pditommaso** [comment]
Try this style 

```
    color: rgb(207, 34, 46);
    text-align: center;
    border-radius: 5px;
    border-color: rgba(31, 35, 40, 0.15);
    border-radius: 6px;
    border-style: solid;
    border-width: 1px;
    font-size: 14px;
    font-weight: 600;
    padding: 5px 16px;
    box-shadow: rgba(31, 35, 40, 0.04) 0px 1px 0px 0px, rgba(255, 255, 255, 0.25) 0px 1px 0px 0px inset;
```

**Comment by munishchouhan** [comment]
> Try this style
> 
> ```
>     color: rgb(207, 34, 46);
>     text-align: center;
>     border-radius: 5px;
>     border-color: rgba(31, 35, 40, 0.15);
>     border-radius: 6px;
>     border-style: solid;
>     border-width: 1px;
>     font-size: 14px;
>     font-weight: 600;
>     padding: 5px 16px;
>     box-shadow: rgba(31, 35, 40, 0.04) 0px 1px 0px 0px, rgba(255, 255, 255, 0.25) 0px 1px 0px 0px inset;
> ```

@pditommaso this is how it looks now
Screenshot 2024-03-11 at 20 55 47

**Comment by pditommaso** [comment]
ok

**Pull request merged**
