### PR TITLE
GHA to submit dependency graph to Github

### PR DESCRIPTION
**Pull request by arnaualcazar**
Created a Github Action to generate and submit the dependency graph to Github to get dependabot alerts.

### CODE REVIEW

**Comment by munishchouhan** [comment]
Dependentbot is not enabled for wave
cc @jordigg

**Comment by munishchouhan** [comment]
tested: 
Screenshot 2024-10-22 at 12 08 07

**Comment by arnaualcazar** [comment]
> Dependentbot is not enabled for wave cc @jordigg

It is enabled right now, but it does not automatically get alerts from Gradle projects. This GHA will allow dependabot to trigger alerts and list vulnerabilities in the dashboard.

**Comment by munishchouhan** [comment]
I am checking here:
Screenshot 2024-10-22 at 12 20 47

**Comment by arnaualcazar** [comment]
I just gave you access, try again

**Comment by munishchouhan** [comment]
I think i was checking at the wrong place:
Screenshot 2024-10-22 at 12 38 49

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
