### PR TITLE
Fix too many requests error

### PR DESCRIPTION
**Pull request by pditommaso**
This PR fixes the error code reported in the response when a rate limits is hit.

### CODE REVIEW

**Comment by pditommaso** [comment]
@fntlnz Can you please review this? POV: when a Docker client submits too many request, a slow down error should be returned and docker should try it again. 

@munishchouhan can you please validate running some tests?

**Comment by fntlnz** [comment]
This change LGTM.

@pditommaso you mean you would expect a retry when trying to pull an image? 
I don't think that there is a  retry mechanism in moby that will retry automatically on 429 however.


## Docker pull

This is what happens with this patch applied
```
docker pull localhost:9090/quay.io/singularity/singularity:v4.0.1-slim
v4.0.1-slim: Pulling from quay.io/singularity/singularity
toomanyrequests: Request exceeded pull rate limit for IP 127.0.0.1
```


This is what happened before this patch

```bash
docker pull localhost:9090/quay.io/singularity/singularity:v4.0.1-slim
v4.0.1-slim: Pulling from quay.io/singularity/singularity
pull access denied for localhost:9090/quay.io/singularity/singularity, repository does not exist or may require 'docker login': denied: Request exceeded pull rate limit for IP 127.0.0.1
```

This is what happens when a docker pull is made against the docker hub directly after hitting the rate limit

```
Using default tag: latest
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```


## Raw requests

For completeness here is what the underlying registry (e.g: docker hub) does when we hit the rate limit there (error through wave)

```
< HTTP/1.1 429 Too Many Requests
< cache-control: no-cache
< content-type: application/json
< date: Thu, 22 Aug 2024 07:55:42 GMT
< content-length: 228
< connection: close
< 
{
  "errors": [
    {
      "code": "TOOMANYREQUESTS",
      "message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
    }
  ]
}
```

This is our error with this PR when we hit the rate limit on wave's side:


```
< HTTP/1.1 429 Too Many Requests
< Content-Type: application/json
< date: Thu, 22 Aug 2024 08:00:39 GMT
< content-length: 107
< connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"errors":[{"code":"TOOMANYREQUESTS","message":"Request exceeded pull rate limit for IP 0:0:0:0:0:0:0:1"}]}
```

**Review by fntlnz — APPROVED** [review]

**Comment by munishchouhan** [comment]
Tested for pull:
Client:
```
docker pull $(wave -i quay.io/singularity/singularity:v4.0.1-slim-arm64 --wave-endpoint http://localhost:9090)
v4.0.1-slim-arm64: Pulling from wt/0774d748ec65/singularity/singularity

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview 6ee0-85-136-67-71.ngrok-free.app/wt/0774d748ec65/singularity/singularity:v4.0.1-slim-arm64
toomanyrequests: Request exceeded pull rate limit for IP 85.136.67.71
```

Logs:
```
11:57:48.722 [io-executor-thread-4] INFO  i.s.w.c.RegistryProxyController - > Request [GET] /v2/wt/0774d748ec65/singularity/singularity/manifests/sha256:03130926ce76b922ee336d09f76e6659852045bf93662d7ba3cf40ec88908896
11:57:48.984 [io-executor-thread-4] INFO  i.s.w.c.RegistryProxyController - > Request [GET] /v2/wt/0774d748ec65/singularity/singularity/manifests/sha256:b9c55fd914933c61c48143538389710c175ae04ec6db1b1f8d57851059841b35
11:57:49.016 [io-executor-thread-5] WARN  io.seqera.wave.ErrorHandler - Request exceeded pull rate limit for IP 127.0.0.1 - Request: GET /v2/wt/0774d748ec65/singularity/singularity/manifests/sha256:b9c55fd914933c61c48143538389710c175ae04ec6db1b1f8d57851059841b35
```

**Comment by munishchouhan** [comment]
Tested for builds:

Client:
```
% wave --conda-package salmon --wave-endpoint http://localhost:9090
Wave invalid response: [429] {"message":"Request exceeded build rate limit for IP 127.0.0.1"}
```

Logs:
```
12:04:06.892 [io-executor-thread-3] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Submit build request: BuildRequest[containerId=4e47217b0900fad0; targetImage=docker.io/hrma017/dev:salmon--4e47217b0900fad0; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null, workflowId=null); dockerFile=FROM mambaorg/micromamba:1.5.8-lunar (more omitted); condaFile=channels: (more omitted); spackFile=null; buildId=4e47217b0900fad0_1, maxDuration=PT15M]
12:04:06.925 [io-executor-thread-2] WARN  io.seqera.wave.ErrorHandler - Request exceeded build rate limit for IP 127.0.0.1 - Request: POST /v1alpha2/container
```

**Pull request merged**
