### PR TITLE
Add support for container scan to Job manager

### PR DESCRIPTION
**Pull request by pditommaso**
This PR adds the support for Container scan to Job manager 

Solves #623

### CODE REVIEW

**Comment by pditommaso** [comment]
This works using Docker. Likely it's missing implementing the use of Job (instead of Pod) in the KubeScanStrategy 

https://github.com/seqeralabs/wave/blob/372105efd330e13c294d8cd506c8621b54bfdc75/src/main/groovy/io/seqera/wave/service/scan/KubeScanStrategy.groovy#L89-L89

**Comment by munishchouhan** [comment]
> This works using Docker. Likely it's missing implementing the use of Job (instead of Pod) in the KubeScanStrategy
> 
> https://github.com/seqeralabs/wave/blob/372105efd330e13c294d8cd506c8621b54bfdc75/src/main/groovy/io/seqera/wave/service/scan/KubeScanStrategy.groovy#L89-L89

Sure, I will add the job for scan

**Comment by munishchouhan** [comment]
rest of the tests are failing because of this error coming from: Working on fixing it
https://github.com/seqeralabs/wave/blob/9e48f497f61e72b90a7bdc134880c37dd2354e7d/src/main/groovy/io/seqera/wave/configuration/ScanConfig.groovy#L76-L81
```
Caused by: java.nio.file.FileSystemException: /build: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at io.seqera.wave.configuration.ScanConfig.memoizedMethodPriv$getCacheDirectory(ScanConfig.groovy:79)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at io.seqera.wave.configuration.ScanConfig.init(ScanConfig.groovy:101)
```

**Comment by pditommaso** [comment]
Better to update the branch with latest changes from `build-v2`

**Comment by pditommaso** [comment]
How is going with the scan

**Comment by munishchouhan** [comment]
> How is going with the scan?

tests has been fixed
No I will test locally building some container

**Comment by pditommaso** [comment]
Once the tests are green, you will to update with the upstream branch

**Comment by munishchouhan** [comment]
Tested with docker, scan is completed but scan page is still showing it in progress, I will work on fixing it

**Comment by pditommaso** [comment]
Sounds good!

**Comment by pditommaso** [comment]
> Tested with docker, scan is completed but scan page is still showing it in progress, I will work on fixing it

I may have missed this comment

**Comment by pditommaso** [comment]
Ok fixed the scan problem 👉 2e5c1af7

**Pull request merged**
