### PR TITLE
Refactor BuildRequest class

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will do the following changes:
1. take out computeDigest and makeTarget of build request construtor
2. make constructor canonical 
3. fix dependent classes and tests

### CODE REVIEW

**Comment by munishchouhan** [comment]
Testing the changes in local

**Comment by munishchouhan** [comment]
2. Test build for docker image + conda + amd64
```
% wave --wave-endpoint http://localhost:9090 --conda-package salmon  --tower-token "eyJ0aWQiOiAxfS5jNTc5MmVlMzZiYThiZDE1NjE4NjAzODEwOTI2NDE1YTM1MDgzODIw" --tower-endpoint http://localhost:8000/api
4837ea38a478.ngrok.app/wt/dfe717b2518f/hrma017/dev:salmon--a1e7965ee5bb914e
```

Logs:
```
15:10:04.525 [io-executor-thread-2] DEBUG i.s.w.s.i.ContainerInspectServiceImpl - Build credentials for repository: hrma017/dev => RegistryCredentials[username=hrma017; password=dck****]
15:10:04.535 [io-executor-thread-2] DEBUG i.seqera.wave.http.HttpClientFactory - Creating new neverRedirectsHttpClient: jdk.internal.net.http.HttpClientImpl@5bce1bca(2)
15:10:04.535 [io-executor-thread-2] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=docker.io/hrma017/dev:salmon--a1e7965ee5bb914e; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null) => RegistryCredentials[username=hrma017; password=dck****]
15:10:05.774 [io-executor-thread-2] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Submit build request: BuildRequest[containerId=a1e7965ee5bb914e; targetImage=hrma017/dev:salmon--a1e7965ee5bb914e; identity=PlatformId(user=User(id:1, userName:hrma017, email:hrma017@gmail.com), workspaceId=null, accessToken=eyJ0aWQiOi.., towerEndpoint=http://localhost:8000/api); dockerFile=FROM mambaorg/micromamba:1.5.8-lunar (more omitted); condaFile=channels: (more omitted); spackFile=null; buildId=a1e7965ee5bb914e_1]
15:10:05.787 [io-executor-thread-1] DEBUG i.s.w.s.builder.DockerBuildStrategy - Build run command: docker run --rm -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/a1e7965ee5bb914e_1:/Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/a1e7965ee5bb914e_1 -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/a1e7965ee5bb914e_1/config.json:/kaniko/.docker/config.json:ro --platform linux/amd64 gcr.io/kaniko-project/executor:v1.19.2 --dockerfile /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/a1e7965ee5bb914e_1/Containerfile --context /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/a1e7965ee5bb914e_1/context --destination hrma017/dev:salmon--a1e7965ee5bb914e --cache=true --custom-platform linux/amd64 --cache-repo hrma017/cache
15:10:05.787 [io-executor-thread-2] DEBUG i.s.w.controller.ContainerController - New container request fulfilled - token=dfe717b2518f; expiration=2024-04-17T14:10:05.781539Z; container=hrma017/dev:salmon--a1e7965ee5bb914e; build=a1e7965ee5bb914e_1; identity=PlatformId(user=User(id:1, userName:hrma017, email:hrma017@gmail.com), workspaceId=null, accessToken=eyJ0aWQiOi.., towerEndpoint=http://localhost:8000/api)
15:10:05.793 [io-executor-thread-3] WARN  i.s.w.f.TraceSlowEndpointPublisher - Slow request detected - elapsed time PT2.949S
- POST /v1alpha2/container
- request headers: 
   Content-Length=420
   Host=localhost:9090
   User-Agent=Java-http-client/21.0.2
   Content-Type=application/json
- status: 200 OK

15:10:38.927 [default-nioEventLoopGroup-2-2] TRACE i.s.w.s.p.socket.PairingWebSocket - Receiving heartbeat - endpoint: http://localhost:8000/api [sessionId: RxFVR8ikBE8OUSqIjo6Qvg==]
15:11:28.922 [default-nioEventLoopGroup-2-2] TRACE i.s.w.s.p.socket.PairingWebSocket - Receiving heartbeat - endpoint: http://localhost:8000/api [sessionId: RxFVR8ikBE8OUSqIjo6Qvg==]
15:12:18.928 [default-nioEventLoopGroup-2-2] TRACE i.s.w.s.p.socket.PairingWebSocket - Receiving heartbeat - endpoint: http://localhost:8000/api [sessionId: RxFVR8ikBE8OUSqIjo6Qvg==]
15:12:34.361 [io-executor-thread-1] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=docker.io/hrma017/dev:salmon--a1e7965ee5bb914e; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null) => RegistryCredentials[username=hrma017; password=dck****]
15:12:34.847 [io-executor-thread-1] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Build request a1e7965ee5bb914e_1 completed with status=0
```

**Comment by munishchouhan** [comment]
4. Test build with dockerfile 
```
% wave --wave-endpoint  http://localhost:9090  -f Dockerfile --tower-token "eyJ0aWQiOiAxfS5jNTc5MmVlMzZiYThiZDE1NjE4NjAzODEwOTI2NDE1YTM1MDgzODIw" --tower-endpoint http://localhost:8000/api
4837ea38a478.ngrok.app/wt/427c232262aa/hrma017/dev:fbd5412d4a868ca5
```

Logs:
```
15:21:45.357 [io-executor-thread-11] DEBUG i.s.w.s.i.ContainerInspectServiceImpl - Build credentials for repository: hrma017/dev => RegistryCredentials[username=hrma017; password=dck****]
15:21:45.358 [io-executor-thread-11] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=docker.io/hrma017/dev:fbd5412d4a868ca5; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null) => RegistryCredentials[username=hrma017; password=dck****]
15:21:45.782 [io-executor-thread-11] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Submit build request: BuildRequest[containerId=fbd5412d4a868ca5; targetImage=hrma017/dev:fbd5412d4a868ca5; identity=PlatformId(user=User(id:1, userName:hrma017, email:hrma017@gmail.com), workspaceId=null, accessToken=eyJ0aWQiOi.., towerEndpoint=http://localhost:8000/api); dockerFile=from redis:latest; condaFile=null; spackFile=null; buildId=fbd5412d4a868ca5_1]
15:21:45.783 [io-executor-thread-11] DEBUG i.s.w.controller.ContainerController - New container request fulfilled - token=427c232262aa; expiration=2024-04-17T14:21:45.783015Z; container=hrma017/dev:fbd5412d4a868ca5; build=fbd5412d4a868ca5_1; identity=PlatformId(user=User(id:1, userName:hrma017, email:hrma017@gmail.com), workspaceId=null, accessToken=eyJ0aWQiOi.., towerEndpoint=http://localhost:8000/api)
15:21:45.784 [io-executor-thread-9] DEBUG i.s.w.s.builder.DockerBuildStrategy - Build run command: docker run --rm -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/fbd5412d4a868ca5_1:/Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/fbd5412d4a868ca5_1 -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/fbd5412d4a868ca5_1/config.json:/kaniko/.docker/config.json:ro --platform linux/amd64 gcr.io/kaniko-project/executor:v1.19.2 --dockerfile /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/fbd5412d4a868ca5_1/Containerfile --context /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/fbd5412d4a868ca5_1/context --destination hrma017/dev:fbd5412d4a868ca5 --cache=true --custom-platform linux/amd64 --cache-repo hrma017/cache
15:21:45.784 [io-executor-thread-10] WARN  i.s.w.f.TraceSlowEndpointPublisher - Slow request detected - elapsed time PT1.271S
- POST /v1alpha2/container
- request headers: 
   Content-Length=255
   Host=localhost:9090
   User-Agent=Java-http-client/21.0.2
   Content-Type=application/json
- status: 200 OK

15:21:53.384 [io-executor-thread-9] DEBUG i.s.wave.core.RegistryProxyService - Credentials for route path=docker.io/hrma017/dev:fbd5412d4a868ca5; identity=PlatformId(user=null, workspaceId=null, accessToken=null, towerEndpoint=null) => RegistryCredentials[username=hrma017; password=dck****]
15:21:53.854 [io-executor-thread-9] INFO  i.s.w.s.b.ContainerBuildServiceImpl - == Build request fbd5412d4a868ca5_1 completed with status=0
15:21:53.889 [io-executor-thread-10] INFO  i.s.w.s.scan.DockerScanStrategy - Launching container scan for buildId: fbd5412d4a868ca5_1 with scanId 65d26054f77f
15:21:53.891 [io-executor-thread-10] DEBUG i.s.w.s.scan.DockerScanStrategy - Container scan command: docker run --rm -w /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/scan-65d26054f77f -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/scan-65d26054f77f:/Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/scan-65d26054f77f:rw -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/.trivy-cache:/root/.cache/:rw -v /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/scan-65d26054f77f/config.json:/root/.docker/config.json:ro aquasec/trivy:0.47.0 --quiet image --timeout 10m --format json --output /Users/munish.chouhan/main_ground/wave/master/wave/build-workspace/scan-65d26054f77f/report.json hrma017/dev:fbd5412d4a868ca5
15:21:59.534 [io-executor-thread-10] INFO  i.s.w.s.scan.DockerScanStrategy - Container scan completed with id: 65d26054f77f
```

**Comment by pditommaso** [comment]
ok, nice. is it ready for review

**Comment by munishchouhan** [comment]
@pditommaso its ready for review

**Comment by pditommaso** [comment]
Good

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
