### PR TITLE
Update Spack version to `develop` (signedoff commits)

### PR DESCRIPTION
**Pull request by marcodelapierre**
Spack version in use for Wave is `default`, as per infrastructure design decision.

Identical to https://github.com/seqeralabs/wave/pull/354, but with signed-off commits.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
@bebosudo can you approve this one? identical to #354 as agreed, but with all commits being signed off.

**Comment by marcodelapierre** [comment]
Also @bebosudo 

for consistency, I suggest to bump update the container images above to 
```
cr.seqera.io /public/spack/spack/ubuntu-jammy:devlop
```


- https://github.com/seqeralabs/infrastructure/blob/4232145b82c9f3e888eeb34cdfd5cfa6e8d12645/.github/workflows/spack-mirror.yaml#L12
- https://github.com/seqeralabs/test-nf-tower-cloud-gha-dev-branch-pr/blob/55b26328a50e8c91c241e0b404dc484d99e4f731/.github/workflows/spack-mirror.yaml#L12

and finally, make sure that image is available in our registry (not the case right now).   Thank you

**Comment by pditommaso** [comment]
I've created a baseline PR https://github.com/seqeralabs/wave/pull/386 against which merge all Spack related stuff and test altogether

**Comment by bebosudo** [comment]
> for consistency, I suggest to bump update the container images above to
> 
> ```
> cr.seqera.io/public/spack/spack/ubuntu-jammy:develop
> ```

The reason for keeping the image at `cr.seqera.io/spack/wave/spack/ubuntu-jammy:develop` is that the `cr.seqera.io/spack/` project on Harbor is a proxy project, configured to fetch images from our ECR in AWS to cache them. This is because to talk to ECR we can configure a role to be assumed by our GHActions and enforce it on a specific repo, while to upload images to a non-proxy project on Harbor we need to set secrets.
Note that the `cr.seqera.io/spack/` is a public repo too, so images can still be downloaded freely:
```
[alberto@fedora]$ docker pull cr.seqera.io/spack/wave/spack/ubuntu-jammy:develop
...
c16b655cbba8ccf44e2ade5ea52d112da8d3963452ee6c4818a5a4c6c1a4feaf
```

Could you share more details on this request?

**Comment by marcodelapierre** [comment]
@bebosudo oops my previous message lacked some info. I was just suggesting to make sure that these other two locations across the codebases also point to the `cr.seqera.io` image:

- https://github.com/seqeralabs/infrastructure/blob/4232145b82c9f3e888eeb34cdfd5cfa6e8d12645/.github/workflows/spack-mirror.yaml#L12
- https://github.com/seqeralabs/test-nf-tower-cloud-gha-dev-branch-pr/blob/55b26328a50e8c91c241e0b404dc484d99e4f731/.github/workflows/spack-mirror.yaml#L12

Does it make sense?

**Comment by marcodelapierre** [comment]
On the public availability of the images. 

This works for me:
```
$ docker pull cr.seqera.io/public/spack/spack/ubuntu-jammy:v0.20.0
v0.20.0: Pulling from public/spack/spack/ubuntu-jammy
...
```

but other tags do not work:
```
$ docker pull cr.seqera.io/public/spack/spack/ubuntu-jammy:develop
Error response from daemon: unknown: artifact public/spack/spack/ubuntu-jammy:develop not found
```

**Comment by marcodelapierre** [comment]
Continuing conversation in #386.

**Pull request merged**
