### PR TITLE
ProxyClient v2

### PR DESCRIPTION
**Pull request by pditommaso**
This PR implements the Wave ProxyClient using the Micronaut HTTP client instead of Java SDK one, based [on the work done](https://github.com/seqeralabs/wave/pull/306).

Most tests pass, however, it looks like there's a problem when retrieving a binary stream by using the following method 

https://github.com/seqeralabs/wave/blob/51a22d80416adb4cf382c2991ca942333da0b56c/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L107-L114

The response body (stream) is always `null`. @munishchouhan have you encountered this problem?

### CODE REVIEW

**Comment by pditommaso** [comment]
Ok, the error is a bit more clear. It looks like `InputStream` is not recognized a decoding type 

```
Caused by: io.micronaut.http.codec.CodecException: Error decoding stream for type [class java.io.InputStream]: Cannot construct instance of `java.io.InputStream` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (byte[])"{"name":"library/hello-world","tags":["latest","linux","nanoserver","nanoserver-1709","nanoserver-1803","nanoserver-1809","nanoserver-ltsc2022","nanoserver-sac2016","nanoserver1709"]}
"; line: 1, column: 1]
	at io.micronaut.json.codec.MapperMediaTypeCodec.decode(MapperMediaTypeCodec.java:193)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:279)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:217)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:191)
	at io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:110)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2186)
	... 55 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.io.InputStream` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (byte[])"{"name":"library/hello-world","tags":["latest","linux","nanoserver","nanoserver-1709","nanoserver-1803","nanoserver-1809","nanoserver-ltsc2022","nanoserver-sac2016","nanoserver1709"]}
"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1360)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3866)
	at io.micronaut.jackson.databind.JacksonDatabindMapper.readValue(JacksonDatabindMapper.java:119)
	at io.micronaut.json.codec.MapperMediaTypeCodec.decode(MapperMediaTypeCodec.java:190)
	... 61 common frames omitted
```

**Comment by munishchouhan** [comment]
@pditommaso I don't remember, But I will check using this PR and let you know

**Comment by marcodelapierre** [comment]
> But I will check using this PR and let you know

Thank you Munish

**Comment by pditommaso** [comment]
@munishchouhan any progress on this?

**Comment by munishchouhan** [comment]
> @munishchouhan any progress on this?

I just started working on it, I will comment on the updates here.

**Comment by munishchouhan** [comment]
@pditommaso I think InputStream is not working because we are using a Blocking HTTP client, which requires a concrete class. We can use String instead
or we can consider 
https://micronaut-projects.github.io/micronaut-docs-mn3/3.2.5/api/io/micronaut/http/client/StreamingHttpClient.html

**Comment by pditommaso** [comment]
String is a now go because this is meant to be used also to stream large binary data.

**Comment by munishchouhan** [comment]
Checking with Micronaut team, if they have any idea about it 
https://github.com/micronaut-projects/micronaut-core/issues/10256

**Comment by munishchouhan** [comment]
response from Micronaut
`don't believe input stream is supported you can use byte[] and wrap the return value in a ByteArrayInputStream`

**Comment by pditommaso** [comment]
We have been recommended to look into the StreamingHttpClient using these deps 

```
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.micronaut.reactor:micronaut-reactor-http-client")

```

An example here: 


https://github.com/sdelamo/micronaut-example-cli-datastream/blob/main/src/main/java/example/micronaut/DownloadCommand.java#L28-L78


In our case tho we should not save to a file but send the stream back.

**Comment by munishchouhan** [comment]
I will look into it

**Comment by pditommaso** [comment]
The main change is that the [httpClient](https://github.com/seqeralabs/wave/blob/96d3ae11ac20591ece83e098e42b855f43c0770c/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L53-L53) should become a `ReactorStreamingHttpClient` 

along with the [this line](https://github.com/seqeralabs/wave/blob/96d3ae11ac20591ece83e098e42b855f43c0770c/src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy#L207-L207) should become  

```
final Flux<HttpResponse<ByteBuffer>> response = httpClient.exchangeStream(request)
``` 

Which impact all the ProxyClient API design that should become async

**Comment by munishchouhan** [comment]
Or should we use ReactorStreamingHttpClient only in getStream()?
and then convert this FileOutputStream 
https://github.com/sdelamo/micronaut-example-cli-datastream/blob/a3006074ac146e35a6416fc974ed8c43853114ae/src/main/java/example/micronaut/DownloadCommand.java#L61 
To FileInputStream
https://stackoverflow.com/questions/7610926/fileoutputstream-into-fileinputstream

**Comment by pditommaso** [comment]
The all share this logic that's not trivial

**Comment by pditommaso** [comment]
But I see you point, [this could](https://github.com/seqeralabs/wave/blob/96d3ae11ac20591ece83e098e42b855f43c0770c/src/main/groovy/io/seqera/wave/core/RegistryProxyService.groovy#L141-L141) become a normal get. 

and make use the streaming client only here 

https://github.com/seqeralabs/wave/blob/96d3ae11ac20591ece83e098e42b855f43c0770c/src/main/groovy/io/seqera/wave/controller/RegistryProxyController.groovy#L342-L353

**Comment by pditommaso** [comment]
Closing this in favour of #357

**Pull request closed without merging**
