### PR TITLE
Remove GitHub workflows for legacy docs site

### PR DESCRIPTION
**Pull request by jason-seqera**
This no longer builds the public documentation.

@pditommaso, I think we can remove this? The public Wave documentation now lives at: https://docs.seqera.io/wave/

And the preview build this creates is no longer accurate, because it uses MkDocs.

Local preview is possible with:

```
docker run -i -t -p 3000:3000 -v $PWD/docs:/home/node/app/docs ghcr.io/seqeralabs/docs-previewer/docs-previewer:latest
```

### CODE REVIEW

**Comment by pditommaso** [comment]
Aside from this, it would be nice to keep containers e.g. `ghcr.io/seqeralabs/docs-previewer/docs-previewer` in our Habor repo ie. `cr.seqera.io/public/docs-previewer` 

Tagging @bebosudo for visibility.

**Comment by jason-seqera** [comment]
cc @MythicalFish on container location. Thanks!

**Comment by bebosudo** [comment]
> Aside from this, it would be nice to keep containers e.g. `ghcr.io/seqeralabs/docs-previewer/docs-previewer` in our Habor repo ie. `cr.seqera.io/public/docs-previewer`

That container is already there, Jake pushed it on November 9.

**Comment by pditommaso** [comment]
Then let's update the readme https://github.com/seqeralabs/wave/blob/3619dbb402c97f3d3e1be09c2868baede3e62fd0/docs.sh#L21

**Pull request merged**
